version: '3.8'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: php-dockerfile
    image: boxbilling/php
    container_name: app-boxbilling
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.build/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver-boxbilling
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: webserver
      SERVICE_TAGS: dev
    ports:
      - "8004:80"
    volumes:
      - ./:/var/www
      - ./.build/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db-boxbilling
    # restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: boxbilling
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./.build/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local